image: node:latest

stages:
  - build
  - test
  - deploy
  - release

build:
  stage: build
  script:
    - yarn install
    - yarn build:locales && yarn build:js

  artifacts:
    paths:
      - public
