image: node:latest

stages:
  - build
  - test
  - deploy
  - release

build:
  stage: build
  script:
    - yarn install
    - yarn build:locales && yarn build:js

  artifacts:
    paths:
      - Lodger-019a13212fa4.json

deploy:
  stage: deploy
  script:
    - npm publish
